info:
	echo "Availables commands: warehouse_up, warehouse_down, warehouse_down_all"

warehouse_up:
	docker-compose up -d

warehouse_down:
	docker-compose down --volumes

warehouse_down_all:
	docker-compose down --volumes --rmi all
